import { ApiProperty } from '@nestjs/swagger';

export class AiResponseTaskDto {
  @ApiProperty({
    description: 'Task title generated by AI',
    example: 'Define app requirements and features',
  })
  title: string;
}

export class AiResponseDto {
  @ApiProperty({
    description: 'Array of tasks generated by AI',
    type: [AiResponseTaskDto],
  })
  tasks: AiResponseTaskDto[];
}
