import {
  Injectable,
  BadGatewayException,
  ServiceUnavailableException,
  UnauthorizedException,
  HttpException,
  UnprocessableEntityException,
  Logger,
} from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import axios, { AxiosError } from "axios";
import { GeminiProvider } from "./providers/gemini.provider";
import { TasksRepository } from "../tasks/tasks.repository";
import { GenerateTasksDto } from "./dto/generate-tasks.dto";
import { Task } from "../tasks/entities/task.entity";
import { AiResponseDto } from "./dto/ai-response.dto";

@Injectable()
export class AiService {
  private readonly logger = new Logger(AiService.name);

  constructor(
    private readonly geminiProvider: GeminiProvider,
    private readonly tasksRepository: TasksRepository,
    private readonly configService: ConfigService,
  ) {}

  async generateTasks(generateTasksDto: GenerateTasksDto): Promise<Task[]> {
    const { objective, apiKey } = generateTasksDto;

    const prompt = this.buildPrompt(objective);

    let response: string;
    try {
      const geminiApiUrl = this.configService.get<string>("gemini.apiUrl");
      const geminiModel = this.configService.get<string>("gemini.model");

      response = await this.geminiProvider.complete(
        prompt,
        apiKey,
        geminiModel,
        geminiApiUrl,
      );
    } catch (error) {
      // If error is already an HttpException, re-throw it
      if (error instanceof HttpException) {
        throw error;
      }
      this.handleLlmError(error);
    }

    // Parse and validate response
    const parsedResponse = this.parseAndValidateResponse(response);

    // Persist tasks
    const createdTasks: Task[] = [];
    for (const taskData of parsedResponse.tasks) {
      const task = await this.tasksRepository.create({
        title: taskData.title,
      });
      // Mark as AI generated by updating the entity
      await this.tasksRepository.update(task.id, {});
      // Re-fetch to get the updated task (add isAiGenerated in next update)
      const updatedTask = await this.tasksRepository.findOne(task.id);
      if (updatedTask) {
        updatedTask.isAiGenerated = true;
        createdTasks.push(updatedTask);
      }
    }

    return createdTasks;
  }

  private buildPrompt(objective: string): string {
    return `Você é um assistente de produtividade. Sua única função é receber um objetivo e retornar uma lista de tarefas acionáveis.

REGRAS ESTRITAS:
- Retorne APENAS um objeto JSON válido, sem texto antes ou depois.
- O JSON deve seguir EXATAMENTE este formato: {"tasks": [{"title": "string"}, ...]}
- Gere entre 3 e 8 tarefas práticas e específicas.
- Cada título deve ser uma ação clara, começando com verbo no infinitivo.
- NÃO inclua explicações, markdown, blocos de código ou qualquer outro texto.

Objetivo do usuário: ${objective}`;
  }

  private parseAndValidateResponse(response: string): AiResponseDto {
    let parsed: unknown;

    try {
      parsed = JSON.parse(response);
    } catch {
      throw new BadGatewayException(
        "A IA retornou uma resposta em formato inesperado.",
      );
    }

    if (!parsed || typeof parsed !== "object") {
      throw new BadGatewayException(
        "A IA retornou uma resposta em formato inesperado.",
      );
    }

    const data = parsed as Record<string, unknown>;

    if (!("tasks" in data)) {
      throw new BadGatewayException(
        "A resposta da IA não contém o formato esperado.",
      );
    }

    const tasks = data.tasks;
    if (!Array.isArray(tasks)) {
      throw new BadGatewayException(
        "A resposta da IA não contém o formato esperado.",
      );
    }

    if (tasks.length === 0) {
      throw new UnprocessableEntityException(
        "A IA não conseguiu gerar tarefas para este objetivo.",
      );
    }

    return { tasks: tasks as Array<{ title: string }> };
  }

  private handleLlmError(error: unknown): never {
    if (axios.isAxiosError(error)) {
      const axiosError = error as AxiosError;

      // HTTP status codes
      if (axiosError.response) {
        const status = axiosError.response.status;

        if (status === 401 || status === 403) {
          throw new UnauthorizedException("API Key inválida ou sem permissão.");
        }

        if (status === 429) {
          throw new HttpException(
            "Limite de requisições da API de IA atingido.",
            429,
          );
        }

        if (status >= 500) {
          throw new BadGatewayException(
            "A IA retornou uma resposta em formato inesperado.",
          );
        }
      }

      // Timeout
      if (axiosError.code === "ECONNABORTED") {
        throw new ServiceUnavailableException(
          "O serviço de IA não respondeu a tempo. Tente novamente.",
        );
      }

      // Network error
      if (axiosError.message === "Network Error") {
        throw new BadGatewayException("Erro de conexão com o serviço de IA.");
      }
    }

    // Generic error
    throw new BadGatewayException(
      "A IA retornou uma resposta em formato inesperado.",
    );
  }
}
