import { ApiProperty } from '@nestjs/swagger';

export class TaskResponseDto {
  @ApiProperty({
    description: 'Unique task identifier',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  id: string;

  @ApiProperty({
    description: 'Task title',
    example: 'Design database schema',
  })
  title: string;

  @ApiProperty({
    description: 'Whether the task is completed',
    example: false,
  })
  isCompleted: boolean;

  @ApiProperty({
    description: 'Whether the task was generated by AI',
    example: false,
  })
  isAiGenerated: boolean;

  @ApiProperty({
    description: 'Task creation timestamp',
    example: '2026-04-16T21:08:34.000Z',
  })
  createdAt: Date;

  @ApiProperty({
    description: 'Last update timestamp',
    example: '2026-04-16T21:08:34.000Z',
  })
  updatedAt: Date;
}
